#!/bin/bash

hey=$(ls -lh $1 |wc -l)

if [ $# -ne 1 ]

then
	echo "This script requires the right dir path for it to work"
	echo "You need to try again"
	exit 1
fi

echo "Oma have $(($hey-1)) lines in this $1"
