#!/bin/bash

#num=1

#while [ $num -le 7 ]
#do
#	echo $num
#	num=$(($num+1))
#	sleep 1
#done

while [ -f ~/bash/log ]
do
	echo "Users log file exit as at $(date)"
sleep 10
done
	echo "Users file is Missing as at $(date)"
